# Generated by Django 3.0 on 2019-12-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adddate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
