# Generated by Django 3.0 on 2019-12-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_scrapper', '0002_client_adddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adddate',
            new_name='created',
        ),
    ]
