# Generated by Django 3.0 on 2019-12-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_scrapper', '0004_auto_20191216_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='updated',
        ),
    ]
