# Generated by Django 3.0 on 2019-12-16 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_scrapper', '0005_remove_client_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
