# Generated by Django 3.0 on 2020-01-08 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_scrapper', '0006_auto_20191216_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsh_scrapper.Client')),
            ],
        ),
    ]
